###
GET http://ikeja.localhost:7000/api/resident/get_last_alert
Cookie: session=MTYzNDk5MzQ3MHxOd3dBTkV0UFJGTkxSVWRSVms1WVNraFBSMHhMUVZKVFFrSlpRa0ZaUkZORE1saEpTRWRIUmsxTU5GSlRRelpRVkVaSVMwdFZXRkU9fOQW1JgVv60Iv1ki9cehk4KAA6GiFFXueh0vfBklYNqF
Content-Type: application/json;charset=UTF-8
